### ISSUE TITLE
Create holdings mapping JSON

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/folio-airflow#20]
Start with https://github.com/FOLIO-FSE/MARC21-To-FOLIO/blob/main/maps/mfhd_to_holdings_default.json

Put in https://github.com/sul-dlss/folio-airflow in project root.

**Comment by shelleydoljack** [comment]
Started a mapping spreadsheet: https://docs.google.com/spreadsheets/d/1FCR1rsgRDonafl7FEfbAF4JEoLLKUM0vwDvwA8fx11g/edit?usp=sharing
