### ISSUE TITLE
Test if HRID is deterministic or defined by load order in the Ebsco migration toolchain

### ISSUE THREAD

**Issue by ryanmax** [sul-dlss/folio-airflow#37]
Suggested procedure:
1.  load 10 inventory records
2.  after loading, extract Sirsi ID, HRID and UUID for each inventory record and save this list
3.  delete these 10 inventory records
4.  load the same 10 records again, this time in a different order
5.  extract IDs again and compare to first list

**Comment by jermnelson** [comment]
Created a Jupyter notebook with findings at the https://gist.github.com/jermnelson/2673a4dd769dfaba31a6919be49748b8

**Comment by ryanmax** [comment]
Thank you, Jeremy. This is helpful.

So HRIDs are determined by load order in EBSCO's migration tools and UUIDs are deterministic based on the catkey plus some other string. Any idea what the other string is? I'm betting IndexData wouldn't accidentally choose the same string for Lane/Voyager UUIDs, but it would be helpful to know.

**Comment by jermnelson** [comment]
Hi @ryanmax, the other string is the Okapi URL see https://github.com/FOLIO-FSE/folio_migration_tools/blob/bf2f3afdae7a0cd93686ab86c4ecb06eb4946fbc/migration_tools/marc_rules_transformation/rules_mapper_bibs.py#L87-L92

**Comment by ryanmax** [comment]
Helpful, thanks. Good to know that UUIDs will not be consistent across SUL FOLIO instances. SUL/Lane collisions should be easy to avoid provided IndexData doesn't use the same fixed strings.
