### ISSUE TITLE
Use correct directory to archive DAG Run JSON artifacts

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/folio-airflow#51]
We should be looking for the Bib, Holdings, and Item transformation JSON artifacts in the `/opt/airflow/migration/results` directory at: https://github.com/sul-dlss/folio-airflow/blob/e11ca3333877a2943490cee9583c563ba5fdf06e/plugins/folio/helpers.py#L24

Mentioned as part of the work https://github.com/sul-dlss/folio-airflow/issues/48

**Comment by shelleydoljack** [comment]
Currently in a branch: https://github.com/sul-dlss/folio-airflow/blob/7299eb11d2ed161b42ce1fffb1f3b967a4680e8a/plugins/folio/helpers.py#L22
